### ISSUE TITLE
Package not yet promoted

### ISSUE THREAD

**Issue by torynet** [maaaaarco/spaghetti-cmd-loader#25]
I've been using your metadata loader and it's a joy. Thank you for your efforts. The ease of use compared to the other available one is night and day.

Now, I would like to install it into Prod, but I can't. You haven't promoted the package. Is this intentional because you don't yet feel confident about it, or is this just an oversight?

**Comment by maaaaarco** [comment]
@torynet that was a mistake. I just promoted the latest package, you should be able to install it ;)
